<!--一级标题-->name: "波萝格"
<!--二级标题-->description: "Blog"

<!--头像-->avatar: https://XxBo_LuoxX.github.io/images/avatar.png
<!--网站图标-->favicon: https://XxBo_LuoxX.github.io/images/favicon.ico

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 
  email: xiongyunhan@outlook.com
  facebook:
  github: XxBoLuoxX
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube:

footer-text: Copyright (c) 2024 XxBo_LuoxX

url: https://XxBo_LuoxX.github.io

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

